import "./globals.css";
import { Poppins } from 'next/font/google';

const poppins = Poppins({ 
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800', '900'], 
});

export const metadata = {
  title: "Food App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} `}>
        <div className="flex justify-center items-center mb-96">
          {children}
        </div>
      </body>
    </html>
  );
}
